### ISSUE TITLE
Migration guide does not mention pycrypto and ssl library requirements

### ISSUE THREAD

**Issue by aetherknight** [cloudendpoints/endpoints-python#26]
https://cloud.google.com/appengine/docs/python/endpoints/migrating

Not sure that this is the best place to file this, but I had to add both pycrypto and ssl to the `libraries` section of my app.yaml to get endpoints 2 (2.0.0b5) working. Neither were needed to get endpoints 1 working.

```
libraries:
- name: pycrypto
  version: "latest"
- name: ssl
  version: "latest"
```
